baseURL = "https://tonyh.dev/"
languageCode = "en-us"
title = "@TonyHarmelink blogging!"
theme = "m10c"
copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."

[author]
    name = "Tony Harmelink"

[params]
author = "Tony Harmelink"
description = "I'm Tony Harmelink. I work primarily on SysAdmin, DevOps, VMware, and EUC projects. VMware vExpert 2020."
  [[params.social]]
    name = "github"
    url = "https://github.com/tonyharmelink"
  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/tonyharmelink"
